### ISSUE TITLE
date_format helper: nulls passed to format date show as linux epoch 

### ISSUE THREAD

**Issue by adamacus** [jasonmit/ember-intl#212]
When using {{date_format someVal}} where someVal=null in Chrome 44, the helper outputs 12/31/1969.  Personally I was expecting an empty string.  Looking more closely, this seems due to the fact that:

    new Intl.DateTimeFormat().format(null)
    "12/31/1969"

Which is kind of surprising.  Also, passing undefined to this produces the current date, which is even more mystifying, though currently the helper catches undefined values and throws an error.  Should the behavior of the helper here return an empty string?  Happy to PR this change if others agree.

**Comment by caridy** [comment]
Well, the fact is that we are not massaging the value, and instead we just handle it over to `Intl.DateTimeFormat()` instance. Obviously we cannot change the current behavior of IntlDateTimeFormat because it will imply breaking everyone who is relying on that "feature" jejejeje, just like a lot of people rely on `new Intl.DateTimeFormat().format(0)` and `new Intl.DateTimeFormat().format(undefined)`. On the other hand, empty string is very confusing as well. We should probably just go with the status quo here, and let users to conditionally print formatted dates.

**Comment by jasonmit** [comment]
> Should the behavior of the helper here return an empty string?

I think we can conditionally support this. It sounds a lot like what I just introduced to ember-moment, except in ember-moment's case it threw on an empty value.

To solve this, I added `allowEmpty` as a [global config option](https://github.com/stefanpenner/ember-moment#global-allow-empty-dates) and can be local to specific helper instance, ie: {{moment-format date allow-empty=true}}.

I'd be happy to review a PR :+1: And it can be enabled by default.  Please target this against master (2.0-dev) and not 1.x.

**Comment by jasonmit** [comment]
All merged.  I just need to make it accessible through the global option via config/environment.js
